version: '3.7'
services:
  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=production
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge